slave1:
  image: registry.cn-hangzhou.aliyuncs.com/amoy_dkhs/dkhs_mesos_slave
  privileged: true
  restart: always
  ports:
    - "5051:5051"
  environment:
    MESOS_MASTER: zk://192.168.107.208:2181/mesos
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_LOG_DIR: /var/log/mesos
